<div id="grpconfig" class="clearfix">
	<form id="searchspace" class="clearfix">
		<input id="searchexpr" class="fl_left" type="text" />
		<label for="searchexpr" class="fl_left">Enter expression here.</label>
	</form>
	<div id="usrconf" class="fl_left">
		<div id="usrlist">
			<?php
			echo $this -> users;
			?>
		</div>
		<div id="paging" class="clearfix">
			<a class="slidens fl_left" href="#"></a>
		</div>
	</div>
</div>