<link rel="stylesheet" href="css/jstree.css" />
<div id="modeselect" class="fl_left">
	<input type="radio" checked="checked" name="mode_select" id="inclussive" value="1" />
	<label for="inclussive">Only selected categories</label><br/>
	<input type="radio" name="mode_select" id="exclussive" value="0" />
	<label for="exclussive">All unselected</label>
</div>
<a class="nsback fl_right" href="#"></a>
<div id="nscattree" class="fl_left apst_blue">
	<div id="treeview" class="demo" style="height:100px;">
		<ul>
			<li id="phtml_1">
				<a href="#">Root node 1</a>
				<ul>
					<li id="phtml_2">
						<a href="#">Child node 1</a>
						<ul>
							<li id="phtml_2">
								<a href="#">Child node 1</a>
							</li>
							<li id="phtml_3">
								<a href="#">Child node 2</a>
								<ul>
									<li id="phtml_2">
										<a href="#">Child node 1</a>
									</li>
									<li id="phtml_2">
										<a href="#">Child node 1</a>
									</li>
									<li id="phtml_2">
										<a href="#">Child node 1</a>
									</li>
									<li id="phtml_2">
										<a href="#">Child node 1</a>
									</li>
									<li id="phtml_2">
										<a href="#">Child node 1</a>
									</li>
									<li id="phtml_2">
										<a href="#">Child node 1</a>
									</li>
									<li id="phtml_2">
										<a href="#">Child node 1</a>
									</li>
									<li id="phtml_2">
										<a href="#">Child node 1</a>
									</li>
									<li id="phtml_2">
										<a href="#">Child node 1</a>
									</li>
									<li id="phtml_2">
										<a href="#">Child node 1</a>
									</li>
									<li id="phtml_2">
										<a href="#">Child node 1</a>
									</li>
									<li id="phtml_3">
										<a href="#">Child node 2</a>
									</li>
								</ul>
							</li>
						</ul>
					</li>
					<li id="phtml_3">
						<a href="#">Child node 2</a>
					</li>
				</ul>
			</li>
			<li id="phtml_4">
				<a href="#">Root node 2</a>
			</li>
		</ul>
	</div>
	<script type="text/javascript" class="source below">
		$(function() {
			// TO CREATE AN INSTANCE
			// select the tree container using jQuery
			$("#treeview")
			// call `.jstree` with the options object
			.jstree({
				"themes" : {
					"theme" : "apple",
				},
				// the `plugins` array allows you to configure the active plugins on this instance
				"plugins" : ["themes", "html_data", "ui", "crrm", "hotkeys"],
				// each plugin you have included can have its own config object
				"core" : {
					"initially_open" : ["phtml_1"]
				},
				// it makes sense to configure a plugin only if overriding the defaults
			})
			// EVENTS
			// each instance triggers its own events - to process those listen on the container
			// all events are in the `.jstree` namespace
			// so listen for `function_name`.`jstree` - you can function names from the docs
			.bind("loaded.jstree", function(event, data) {
				// you get two params - event & data - check the core docs for a detailed description
			});
		});

	</script>
</div>