<script type="text/javascript">

    changeConfirmationHead('<?php echo $this->Headline;?>');
    changeConfirmationMain('<strong><?php echo $this->Message;?></strong>');
    hideConfirmationBtnRed();
    // Unknown rotation in array normaly it must be on first key no. 2 (layers[2][3])
    
    $('#cat_<?php echo $this->updateCategory; ?> .inner_contain .composites_num').text(parseInt($('#cat_<?php echo $this->updateCategory; ?> .inner_contain .composites_num').text()) + 1);
	$('#cat_<?php echo $this->fromCategory; ?> .inner_contain .composites_num').text(parseInt($('#cat_<?php echo $this->fromCategory; ?> .inner_contain .composites_num').text()) - 1);
	
	$('#composite_<?php echo $this->updateComposite; ?>').remove();			
					
    sRequestSender = 'close';
	
</script>
