<script type="text/javascript">
    sRequestSender = 'close';
    changeConfirmationHead('<?php echo $this->Headline;?>');
    changeConfirmationMain('<strong><?php echo $this->Message;?></strong>');
	hideConfirmationBtnRed();
   // resetConfirmationBtnGreen();
    getAreaData('cats/index', 'cats');
    iTmp = iCurCatIn;
    window.setTimeout(function(){
        moveToCat(iCurCatIn)
    }, 1500);
</script>
